"""Add measurement and uncertainty calculation tables

Revision ID: 82c26a13c474
Revises: 9812e60fbe51
Create Date: 2025-09-01 19:40:10.412445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c26a13c474'
down_revision: Union[str, None] = '9812e60fbe51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
